/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DButton: typeof import('./../src/components/DButton.vue')['default']
    DCard: typeof import('./../src/components/DCard.vue')['default']
    DCheckbox: typeof import('./../src/components/DCheckbox.vue')['default']
    DCodeBlock: typeof import('./../src/components/DCodeBlock.vue')['default']
    DDarkToggle: typeof import('./../src/components/DDarkToggle.vue')['default']
    DDialog: typeof import('./../src/components/DDialog.vue')['default']
    DDropdown: typeof import('./../src/components/DDropdown.vue')['default']
    DIcon: typeof import('./../src/components/DIcon.vue')['default']
    DIconButton: typeof import('./../src/components/DIconButton.vue')['default']
    DIconTitle: typeof import('./../src/components/DIconTitle.vue')['default']
    DLink: typeof import('./../src/components/DLink.vue')['default']
    DLoading: typeof import('./../src/components/DLoading.vue')['default']
    DMarkdown: typeof import('./../src/components/DMarkdown.vue')['default']
    DRadio: typeof import('./../src/components/DRadio.vue')['default']
    DSectionBlock: typeof import('./../src/components/DSectionBlock.vue')['default']
    DSelect: typeof import('./../src/components/DSelect.vue')['default']
    DSwitch: typeof import('./../src/components/DSwitch.vue')['default']
    DTextInput: typeof import('./../src/components/DTextInput.vue')['default']
    DTip: typeof import('./../src/components/DTip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowSource: typeof import('./src/components/ShowSource.vue')['default']
  }
}
